import { createContext, useContext, useState, useEffect } from 'react';
import api from '../api';
import { useAuth } from './AuthContext';

const AuditContext = createContext();

export const AuditProvider = ({ children }) => {
    const { user } = useAuth();
    const [auditLogs, setAuditLogs] = useState([]);
    const [loading, setLoading] = useState(false);

    const fetchAuditLogs = async () => {
        if (!user || user.role !== 'authority') return;
        setLoading(true);
        try {
            const response = await api.get('/audit');
            setAuditLogs(response.data);
        } catch (error) {
            console.error("Failed to fetch audit logs", error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchAuditLogs();
    }, [user]);

    // Local logging helper (used before backend integration or for Client-side only events)
    // Most events are now logged on the server.
    const addAuditLog = async (logData) => {
        // In this system, audit logs are primarily generated by the backend
        // This function can be kept for frontend-only events if needed
        console.log("Frontend Audit Event:", logData);
        // Optionally refresh logs from server
        fetchAuditLogs();
    };

    return (
        <AuditContext.Provider value={{ auditLogs, loading, fetchAuditLogs, addAuditLog }}>
            {children}
        </AuditContext.Provider>
    );
};

export const useAudit = () => {
    const context = useContext(AuditContext);
    if (!context) {
        throw new Error('useAudit must be used within an AuditProvider');
    }
    return context;
};
