import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        // Navbar/Common
        login: "Login",
        register: "Get Started",
        logout: "Logout",
        dashboard: "Dashboard",
        profile: "My Profile",
        appearance: "Appearance",
        lang: "Lang",

        // Landing Page
        heroTitle: "Resilient. Responsive. Ready.",
        heroSubtitle: "The National Disaster Management System for real-time coordination and response.",
        reportIncident: "Report Incident",
        joinVolunteer: "Join as Volunteer",
        liveAlerts: "LIVE ALERTS",

        // Stats
        activeIncidents: "Active Incidents",
        volunteersDeployed: "Volunteers Deployed",
        personnelDeployed: "Personnel Deployed",
        sheltersOpen: "Shelters Open",
        hospitalsActive: "Hospitals Active",
        avgResponseTime: "Avg. Response Time",

        // Role Selection
        selectAccess: "Select Your Access Level",
        roleInstruction: "Choose your operational role to continue to the dashboard.",
        authority: "Authority",
        authorityDesc: "Command Center & Ops",
        volunteer: "Volunteer",
        volunteerDesc: "Field Tasks & Resources",
        citizen: "Citizen",
        citizenDesc: "Report & View Alerts",

        // Auth Pages
        joinDms: "Join DMS",
        bePartNetwork: "Be part of the resilient network. Help your community respond faster and safer.",
        createAccount: "Create Account",
        takesAMinute: "It only takes a minute to start.",
        fullName: "Full Name",
        emailAddress: "Email Address",
        password: "Password",
        confirmPassword: "Confirm Password",
        termsAgree: "I agree to the",
        termsOfService: "Terms of Service",
        privacyPolicy: "Privacy Policy",
        signUp: "Sign Up",
        orJoinWith: "Or join with",
        orContinueWith: "Or continue with",
        alreadyHaveAccount: "Already have an account?",
        signIn: "Sign In",
        enterDetails: "Enter your details to proceed.",
        rememberMe: "Remember me",
        forgotPassword: "Forgot Password?",
        newToDms: "New to DMS?",
        changeRole: "Change Role",
        systemOperational: "System Operational",
        activeUnits: "Active Units",
        access: "Access",
        user: "User",
        guest: "Guest",

        // Emergency & Safety
        emergencyContacts: "Emergency Contacts",
        nationalEmergency: "National Emergency",
        ambulance: "Ambulance",
        fire: "Fire",
        disasterControlRoom: "Disaster Control Room",
        safetyGuidelines: "Safety Guidelines",
        floodSafety: "Flood Safety",
        floodAdvice: "Move to higher ground. Disconnect electrical appliances. Do not walk through moving water.",
        earthquakeSafety: "Earthquake Safety",
        earthquakeAdvice: "Drop, Cover, and Hold On. Stay indoors until shaking stops. Stay away from windows.",
        in: "in",
        testimonials: [
            { id: 1, initials: "JD", name: "John Doe", role: "Volunteer", quote: "The real-time alerts helped me coordinate rescue efforts instantly. This system is a lifesaver." },
            { id: 2, initials: "SA", name: "Sarah Ames", role: "Coordinator", quote: "Managing resources has never been this efficient. We can now deploy help exactly where it's needed." },
            { id: 3, initials: "MR", name: "Michael Ross", role: "First Responder", quote: "Clear communication during disasters is critical. DMS provides exactly that reliability." }
        ],

        // Dashboard & Sidebar
        disasterManagement: "Disaster Management",
        alerts: "Alerts",
        command: "Command",
        logistics: "Logistics",
        audits: "Audits",
        myTasks: "My Tasks",
        resources: "Resources",
        currentView: "Current View",
        quickActions: "Quick Actions",
        createAlert: "Create Alert",
        reportIssue: "Report Issue",
        launchSos: "Launch SOS",
        viewAlerts: "View Alerts",

        // Alerts Page
        systemAlerts: "System Alerts",
        manageBroadcasts: "Manage broadcast notifications",
        edit: "Edit",
        deactivate: "Deactivate",

        // Alert Content
        flashFloodWarning: "Flash Flood Warning",
        heavyRainfall: "Heavy Rainfall",
        roadClosure: "Road Closure",
        wildfireReported: "Wildfire Reported",
        districtA: "District A",
        districtB: "District B",
        highway42: "Highway 42",
        northForest: "North Forest",
        tenMinsAgo: "10m ago",
        oneHourAgo: "1h ago",
        twoHoursAgo: "2h ago",
        fiveMinsAgo: "5m ago",
        operationalOverview: "Operational Overview",
        realTimeAwareness: "Real-time situational awareness",
        incidentTrends: "Incident Trends",
        resourceStatus: "Resource Status",
        recentAlerts: "Recent Critical Alerts",
        vsLastWeek: "vs last week",
        improvement: "improvement",
        time: "Time",
        status: "Status",
        active: "Active",
        inactive: "Inactive",
        activate: "Activate",
        saveChanges: "Save Changes",
        cancel: "Cancel",
        alertDeactivated: "Alert deactivated successfully",
        alertActivated: "Alert activated successfully",
        newAlert: "New Alert",
        alertTitle: "Alert Title",
        alertType: "Alert Type",
        selectType: "Select Type",
        broadcastAlert: "Broadcast Alert",
        critical: "CRITICAL",
        high: "HIGH",
        responding: "Responding",
        resolved: "Resolved",
        newIncidents: "New Incidents",
        available: "Available",
        deployed: "Deployed",
        maintenance: "Maintenance",
        mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat", sun: "Sun",
        flashFlood: "Flash Flood",
        powerOutage: "Hospital Power Outage",
        northZone: "District A - North Zone",
        hospitalLocation: "City General Hospital",
        minsAgo: "mins ago",
        mins: "m",

        // Logistics Page
        resourceManagement: "Resource Management",
        trackAllocateAssets: "Track and allocate assets",
        inventory: "Inventory",
        hospitalsTab: "Hospitals",
        volunteersTab: "Volunteers",
        searchResources: "Search resources...",
        beds: "Beds",
        icu: "ICU",
        units: "Units",
        full: "Full",

        // Logistics Data
        firstAid: "First Aid",
        searchAndRescue: "Search & Rescue",
        warehouseA: "Warehouse A",
        warehouseB: "Warehouse B",
        centralDepot: "Central Depot",
        foodPackets: "Food Packets",
        blankets: "Blankets",
        medKits: "Med Kits",
        cityGeneral: "City General",
        memorialHospital: "Memorial Hospital",

        copyright: "© 2025 Disaster Management System",
        system: "System",
        core: "Core",
        location: "Location",
        totalLogs: "Total Logs"
    },
    es: {
        // Navbar/Common
        login: "Iniciar Sesión",
        register: "Empezar",
        logout: "Cerrar Sesión",
        dashboard: "Panel de Control",
        profile: "Mi Perfil",
        appearance: "Apariencia",
        lang: "Idioma",

        // Landing Page
        heroTitle: "Resiliente. Responsivo. Listo.",
        heroSubtitle: "El Sistema Nacional de Gestión de Desastres para coordinación y respuesta en tiempo real.",
        reportIncident: "Informar Incidente",
        joinVolunteer: "Unirse como Voluntario",
        liveAlerts: "ALERTA EN VIVO",

        // Stats
        activeIncidents: "Incidentes Activos",
        volunteersDeployed: "Voluntarios Desplegados",
        personnelDeployed: "Personal Desplegado",
        sheltersOpen: "Refugios Abiertos",
        hospitalsActive: "Hospitales Activos",
        avgResponseTime: "Tiempo Promedio de Respuesta",

        // Role Selection
        selectAccess: "Seleccione su Nivel de Acceso",
        roleInstruction: "Elija su función operativa para continuar al panel de control.",
        authority: "Autoridad",
        authorityDesc: "Centro de Comando y Operaciones",
        volunteer: "Voluntario",
        volunteerDesc: "Tareas de Campo y Recursos",
        citizen: "Ciudadano",
        citizenDesc: "Informar y Ver Alertas",

        // Auth Pages
        joinDms: "Únete a DMS",
        bePartNetwork: "Forma parte de la red resiliente. Ayuda a tu comunidad a responder más rápido y seguro.",
        createAccount: "Crear Cuenta",
        takesAMinute: "Solo toma un minuto comenzar.",
        fullName: "Nombre Completo",
        emailAddress: "Correo Electrónico",
        password: "Contraseña",
        confirmPassword: "Confirmar Contraseña",
        termsAgree: "Estoy de acuerdo con los",
        termsOfService: "Términos de Servicio",
        privacyPolicy: "Política de Privacidad",
        signUp: "Registrarse",
        orJoinWith: "O únete con",
        orContinueWith: "O continuar con",
        alreadyHaveAccount: "¿Ya tienes una cuenta?",
        signIn: "Iniciar Sesión",
        enterDetails: "Ingrese sus datos para proceder.",
        rememberMe: "Recuérdame",
        forgotPassword: "¿Olvidaste tu contraseña?",
        newToDms: "¿Nuevo en DMS?",
        changeRole: "Cambiar Rol",
        systemOperational: "Sistema Operativo",
        activeUnits: "Unidades Activas",
        access: "Acceso",
        user: "Usuario",
        guest: "Invitado",

        // Emergency & Safety
        emergencyContacts: "Contactos de Emergencia",
        nationalEmergency: "Emergencia Nacional",
        ambulance: "Ambulancia",
        fire: "Bomberos",
        disasterControlRoom: "Sala de Control de Desastres",
        safetyGuidelines: "Pautas de Seguridad",
        floodSafety: "Seguridad ante Inundaciones",
        floodAdvice: "Diríjase a terrenos más altos. Desconecte los aparatos eléctricos. No camine por el agua en movimiento.",
        earthquakeSafety: "Seguridad ante Terremotos",
        earthquakeAdvice: "Agáchese, cúbrase y agárrese. Quédesه adentro hasta que cese el temblor. Aléjese de las ventanas.",
        in: "en",
        testimonials: [
            { id: 1, initials: "JD", name: "Juan Díaz", role: "Voluntario", quote: "Las alertas en tiempo real me ayudaron a coordinar refuerzos al instante. Este sistema salva vidas." },
            { id: 2, initials: "SA", name: "Sara Amés", role: "Coordinadora", quote: "Gestionar recursos nunca ha sido tan eficiente. Ahora podemos desplegar ayuda exactamente donde se necesita." },
            { id: 3, initials: "MR", name: "Miguel Rosas", role: "Primer Respondedor", quote: "La comunicación clara durante desastres es crítica. DMS proporciona exactamente esa confiabilidad." }
        ],

        // Dashboard & Sidebar
        disasterManagement: "Gestión de Desastres",
        alerts: "Alertas",
        command: "Mando",
        logistics: "Logística",
        audits: "Auditorías",
        myTasks: "Mis Tareas",
        resources: "Recursos",
        currentView: "Vista Actual",
        quickActions: "Acciones Rápidas",
        createAlert: "Crear Alerta",
        reportIssue: "Informar Problema",
        launchSos: "Lanzar SOS",
        viewAlerts: "Ver Alertas",

        // Alerts Page
        systemAlerts: "Alertas del Sistema",
        manageBroadcasts: "Gestionar notificaciones de difusión",
        edit: "Editar",
        deactivate: "Desactivar",

        // Alert Content
        flashFloodWarning: "Aviso de Inundación Repentina",
        heavyRainfall: "Lluvia Intensa",
        roadClosure: "Cierre de Carretera",
        wildfireReported: "Incendio Forestal Reportado",
        districtA: "Distrito A",
        districtB: "Distrito B",
        highway42: "Carretera 42",
        northForest: "Bosque del Norte",
        tenMinsAgo: "hace 10m",
        oneHourAgo: "hace 1h",
        twoHoursAgo: "hace 2h",
        fiveMinsAgo: "hace 5m",
        operationalOverview: "Resumen Operativo",
        realTimeAwareness: "Conciencia situacional en tiempo real",
        incidentTrends: "Tendencias de Incidentes",
        resourceStatus: "Estado de los Recursos",
        recentAlerts: "Alertas Críticas Recientes",
        vsLastWeek: "frente a la semana pasada",
        improvement: "mejora",
        time: "Tiempo",
        status: "Estado",
        active: "Activo",
        inactive: "Inactivo",
        activate: "Activar",
        saveChanges: "Guardar Cambios",
        cancel: "Cancelar",
        alertDeactivated: "Alerta desactivada con éxito",
        alertActivated: "Alerta activada con éxito",
        newAlert: "Nueva Alerta",
        alertTitle: "Título de la Alerta",
        alertType: "Tipo de Alerta",
        selectType: "Seleccionar Tipo",
        broadcastAlert: "Emitir Alerta",
        critical: "CRÍTICO",
        high: "ALTO",
        responding: "Respondiendo",
        resolved: "Resuelto",
        newIncidents: "Nuevos Incidentes",
        available: "Disponible",
        deployed: "Desplegado",
        maintenance: "Mantenimiento",
        mon: "Lun", tue: "Mar", wed: "Mié", thu: "Jue", fri: "Vie", sat: "Sáb", sun: "Dom",
        flashFlood: "Inundación Repentina",
        powerOutage: "Corte de Energía en Hospital",
        northZone: "Distrito A - Zona Norte",
        hospitalLocation: "Hospital General de la Ciudad",
        minsAgo: "minutos antes",
        mins: "m",

        // Logistics Page
        resourceManagement: "Gestión de Recursos",
        trackAllocateAssets: "Seguimiento y asignación de activos",
        inventory: "Inventario",
        hospitalsTab: "Hospitales",
        volunteersTab: "Voluntarios",
        searchResources: "Buscar recursos...",
        beds: "Camas",
        icu: "UCI",
        units: "Unidades",
        full: "Lleno",

        // Logistics Data
        firstAid: "Primeros Auxilios",
        searchAndRescue: "Búsqueda y Rescate",
        warehouseA: "Almacén A",
        warehouseB: "Almacén B",
        centralDepot: "Depósito Central",
        foodPackets: "Paquetes de Comida",
        blankets: "Mantas",
        medKits: "Kits Médicos",
        cityGeneral: "Hospital General de la Ciudad",
        memorialHospital: "Hospital Memorial",

        copyright: "© 2025 Sistema de Gestión de Desastres",
        system: "Sistema",
        core: "Núcleo",
        location: "Ubicación",
        totalLogs: "Registros Totales"
    },
    fr: {
        // Navbar/Common
        login: "Connexion",
        register: "Commencer",
        logout: "Déconnexion",
        dashboard: "Tableau de Bord",
        profile: "Mon Profil",
        appearance: "Apparence",
        lang: "Langue",

        // Landing Page
        heroTitle: "Résilient. Réactif. Prêt.",
        heroSubtitle: "Le système national de gestion des catastrophes pour une coordination et une réponse en temps réel.",
        reportIncident: "Signaler un Incident",
        joinVolunteer: "Devenir Bénévole",
        liveAlerts: "ALERTES EN DIRECT",

        // Stats
        activeIncidents: "Incidents Actifs",
        volunteersDeployed: "Bénévole Déployés",
        personnelDeployed: "Personnel Déployé",
        sheltersOpen: "Abris Ouverts",
        hospitalsActive: "Hôpitaux Actifs",
        avgResponseTime: "Temps de Réponse Moyen",

        // Role Selection
        selectAccess: "Sélectionnez votre niveau d'accès",
        roleInstruction: "Choisissez votre rôle opérationnel pour accéder au tableau de bord.",
        authority: "Autorité",
        authorityDesc: "Centre de Commandement et Ops",
        volunteer: "Bénévole",
        volunteerDesc: "Tâches de Terrain et Ressources",
        citizen: "Citoyen",
        citizenDesc: "Signaler et Voir les Alertes",

        // Auth Pages
        joinDms: "Rejoindre DMS",
        bePartNetwork: "Faites partie du réseau résilient. Aidez votre communauté à répondre plus rapidement et plus sûrement.",
        createAccount: "Créer un Compte",
        takesAMinute: "Cela ne prend qu'une minute pour commencer.",
        fullName: "Nom Complet",
        emailAddress: "Adresse E-mail",
        password: "Mot de Passe",
        confirmPassword: "Confirmer le Mot de Passe",
        termsAgree: "J'accepte les",
        termsOfService: "Conditions d'Utilisation",
        privacyPolicy: "Politique de Confidentialité",
        signUp: "S'inscrire",
        orJoinWith: "Ou rejoindre avec",
        orContinueWith: "Ou continuer avec",
        alreadyHaveAccount: "Vous avez déjà un compte ?",
        signIn: "Se Connecter",
        enterDetails: "Entrez vos coordonnées pour continuer.",
        rememberMe: "Se souvenir de moi",
        forgotPassword: "Mot de passe oublié ?",
        newToDms: "Nouveau sur DMS ?",
        changeRole: "Changer de Rôle",
        systemOperational: "Système Opérationnel",
        activeUnits: "Unités Actives",
        access: "Accès",
        user: "Utilisateur",
        guest: "Invité",

        // Emergency & Safety
        emergencyContacts: "Contacts d'Urgence",
        nationalEmergency: "Urgence Nationale",
        ambulance: "Ambulance",
        fire: "Pompiers",
        disasterControlRoom: "Salle de Contrôle des Catastrophes",
        safetyGuidelines: "Consignes de Sécurité",
        floodSafety: "Sécurité Inondation",
        floodAdvice: "Déplacez-vous vers un terrain plus élevé. Débranchez les appareils électriques. Ne marchez pas dans l'eau en mouvement.",
        earthquakeSafety: "Sécurité Séisme",
        earthquakeAdvice: "Baissez-vous, couvrez-vous et agrippez-vous. Restez à l'intérieur jusqu'à ce que les secousses cessent. Tenez-vous loin des fenêtres.",
        in: "à",
        testimonials: [
            { id: 1, initials: "JD", name: "Jean Dupont", role: "Bénévole", quote: "Les alertes en temps réel m'ont aidé à coordonner les secours instantanément. Ce système est vital." },
            { id: 2, initials: "SA", name: "Sarah Amiot", role: "Coordinatrice", quote: "La gestion des ressources n'a jamais été aussi efficace. Nous pouvons désormais déployer l'aide précisément là où elle est nécessaire." },
            { id: 3, initials: "MR", name: "Michel Roux", role: "Premier Répondant", quote: "Une communication claire en cas de catastrophe est cruciale. DMS offre exactement cette fiabilité." }
        ],

        // Dashboard & Sidebar
        disasterManagement: "Gestion des Catastrophes",
        alerts: "Alertes",
        command: "Commandement",
        logistics: "Logistique",
        audits: "Audits",
        myTasks: "Mes Tâches",
        resources: "Ressources",
        currentView: "Vue Actuelle",
        quickActions: "Actions Rapides",
        createAlert: "Créer une Alerte",
        reportIssue: "Signaler un Problème",
        launchSos: "Lancer SOS",
        viewAlerts: "Voir les Alertes",

        // Alerts Page
        systemAlerts: "Alertes Système",
        manageBroadcasts: "Gérer les notifications de diffusion",
        edit: "Modifier",
        deactivate: "Désactiver",

        // Alert Content
        flashFloodWarning: "Alerte de crue soudaine",
        heavyRainfall: "Pluie forte",
        roadClosure: "Fermeture de route",
        wildfireReported: "Feu de forêt signalé",
        districtA: "District A",
        districtB: "District B",
        highway42: "Autoroute 42",
        northForest: "Forêt du Nord",
        tenMinsAgo: "il y a 10m",
        oneHourAgo: "il y a 1h",
        twoHoursAgo: "il y a 2h",
        fiveMinsAgo: "il y a 5m",
        operationalOverview: "Aperçu Opérationnel",
        realTimeAwareness: "Connaissance de la situation en temps réel",
        incidentTrends: "Tendances des Incidents",
        resourceStatus: "État des Ressources",
        recentAlerts: "Alertes Critiques Récentes",
        vsLastWeek: "vs semaine dernière",
        improvement: "amélioration",
        time: "Temps",
        status: "Statut",
        active: "Actif",
        inactive: "Inactif",
        activate: "Activer",
        saveChanges: "Enregistrer les modifications",
        cancel: "Annuler",
        alertDeactivated: "Alerte désactivée avec succès",
        alertActivated: "Alerte activée avec succès",
        newAlert: "Nouvelle Alerte",
        alertTitle: "Titre de l'alerte",
        alertType: "Type d'alerte",
        selectType: "Sélectionner le type",
        broadcastAlert: "Diffuser l'alerte",
        critical: "CRITIQUE",
        high: "HAUT",
        responding: "Intervention",
        resolved: "Résolu",
        newIncidents: "Nouveaux Incidents",
        available: "Disponible",
        deployed: "Déployé",
        maintenance: "Maintenance",
        mon: "Lun", tue: "Mar", wed: "Mer", thu: "Jeu", fri: "Ven", sat: "Sam", sun: "Dim",
        flashFlood: "Inundation Éclair",
        powerOutage: "Coupure de Courant à l'Hôpital",
        northZone: "District A - Zone Nord",
        hospitalLocation: "Hôpital Général de la Ville",
        minsAgo: "il y a quelques minutes",
        mins: "m",

        // Logistics Page
        resourceManagement: "Gestion des Ressources",
        trackAllocateAssets: "Suivi et allocation des actifs",
        inventory: "Inventaire",
        hospitalsTab: "Hôpitaux",
        volunteersTab: "Bénévoles",
        searchResources: "Rechercher des ressources...",
        beds: "Lits",
        icu: "Soins Intensifs",
        units: "Unités",
        full: "Complet",

        // Logistics Data
        firstAid: "Premiers Secours",
        searchAndRescue: "Recherche et Sauvetage",
        warehouseA: "Entrepôt A",
        warehouseB: "Entrepôt B",
        centralDepot: "Dépôt Central",
        foodPackets: "Paquets de Nourriture",
        blankets: "Couvertures",
        medKits: "Kits Médicaux",
        cityGeneral: "Hôpital Général de la Ville",
        memorialHospital: "Hôpital Memorial",

        copyright: "© 2025 Système de gestion des catastrophes",
        system: "Système",
        core: "Cœur",
        location: "Emplacement",
        totalLogs: "Journaux Totaux"
    },
    ar: {
        // Navbar/Common
        login: "تسجيل الدخول",
        register: "بدء الاستخدام",
        logout: "تسجيل الخروج",
        dashboard: "لوحة التحكم",
        profile: "ملفي الشخصي",
        appearance: "المظهر",
        lang: "اللغة",

        // Landing Page
        heroTitle: "صامد. مستجيب. مستعد.",
        heroSubtitle: "النظام الوطني لإدارة الكوارث للتنسيق والاستجابة في الوقت الفعلي.",
        reportIncident: "الإبلاغ عن حادث",
        joinVolunteer: "انضم كمتطوع",
        liveAlerts: "تنبيهات مباشرة",

        // Stats
        activeIncidents: "الحوادث النشطة",
        volunteersDeployed: "المتطوعون المنتشرون",
        personnelDeployed: "الموظفون المنتشرون",
        sheltersOpen: "الملاجئ المفتوحة",
        hospitalsActive: "المستشفيات النشطة",
        avgResponseTime: "متوسط وقت الاستجابة",

        // Role Selection
        selectAccess: "اختر مستوى الوصول الخاص بك",
        roleInstruction: "اختر دورك التشغيلي للمتابعة إلى لوحة التحكم.",
        authority: "سلطة",
        authorityDesc: "مركز القيادة والعمليات",
        volunteer: "متطوع",
        volunteerDesc: "المهام الميدانية والموارد",
        citizen: "مواطن",
        citizenDesc: "الإبلاغ وعرض التنبيهات",

        // Auth Pages
        joinDms: "انضم إلى DMS",
        bePartNetwork: "كن جزءاً من الشبكة الصامدة. ساعد مجتمعك على الاستجابة بشكل أسرع وأكثر أماناً.",
        createAccount: "إنشاء حساب",
        takesAMinute: "يستغرق الأمر دقيقة واحدة فقط للبدء.",
        fullName: "الاسم الكامل",
        emailAddress: "عنوان البريد الإلكتروني",
        password: "كلمة المرور",
        confirmPassword: "تأكيد كلمة المرور",
        termsAgree: "أوافق على",
        termsOfService: "شروط الخدمة",
        privacyPolicy: "سياسة الخصوصية",
        signUp: "إنشاء حساب",
        orJoinWith: "أو انضم بواسطة",
        orContinueWith: "أو استمر بواسطة",
        alreadyHaveAccount: "هل لديك حساب بالفعل؟",
        signIn: "تسجيل الدخول",
        enterDetails: "أدخل بياناتك للمتابعة.",
        rememberMe: "تذكرني",
        forgotPassword: "هل نسيت كلمة المرور؟",
        newToDms: "جديد في DMS؟",
        changeRole: "تغيير الدور",
        systemOperational: "النظام يعمل",
        activeUnits: "الوحدات النشطة",
        access: "وصول",
        user: "مستخدم",
        guest: "ضيف",

        // Emergency & Safety
        emergencyContacts: "جهات اتصال الطوارئ",
        nationalEmergency: "طوارئ وطنية",
        ambulance: "إسعاف",
        fire: "إطفاء",
        disasterControlRoom: "غرفة التحكم في الكوارث",
        safetyGuidelines: "إرشادات السلامة",
        floodSafety: "السلامة من الفيضانات",
        floodAdvice: "انتقل إلى أرض مرتفعة. افصل الأجهزة الكهربائية. لا تمشِ عبر المياه المتحركة.",
        earthquakeSafety: "السلامة من الزلازل",
        earthquakeAdvice: "انخفض، تغطَّ، وتمسك. ابقَ في الداخل حتى يتوقف الاهتزاز. ابقَ بعيداً عن النوافذ.",
        in: "في",
        testimonials: [
            { id: 1, initials: "JD", name: "جون دو", role: "متطوع", quote: "ساعدتني التنبيهات في الوقت الفعلي على تنسيق جهود الإنقاذ على الفور. هذا النظام منقذ للحياة." },
            { id: 2, initials: "SA", name: "سارة أميس", role: "منسق", quote: "لم تكن إدارة الموارد بهذه الكفاءة من قبل. يمكننا الآن نشر المساعدة بالضبط حيث تشتد الحاجة إليها." },
            { id: 3, initials: "MR", name: "مايكل روس", role: "المستجيب الأول", quote: "قنوات الاتصال الواضحة أثناء الكوارث أمر بالغ الأهمية. يوفر DMS هذه الموثوقية بالضبط." }
        ],

        // Dashboard & Sidebar
        disasterManagement: "إدارة الكوارث",
        alerts: "التنبيهات",
        command: "مركز القيادة",
        logistics: "الأمور اللوجستية",
        audits: "التدقيق",
        myTasks: "مهامي",
        resources: "الموارد",
        currentView: "العرض الحالي",
        quickActions: "إجراءات سريعة",
        createAlert: "إنشاء تنبيه",
        reportIssue: "الإبلاغ عن مشكلة",
        launchSos: "إطلاق نداء استغاثة",
        viewAlerts: "عرض التنبيهات",

        // Alerts Page
        systemAlerts: "تنبيهات النظام",
        manageBroadcasts: "إدارة إشعارات البث",
        edit: "تعديل",
        deactivate: "تعطيل",

        // Alert Content
        flashFloodWarning: "تنبيه من فيضان مفاجئ",
        heavyRainfall: "هطول أمطار غزيرة",
        roadClosure: "إغلاق الطريق",
        wildfireReported: "تم الإبلاغ عن حريق غابات",
        districtA: "المنطقة أ",
        districtB: "المنطقة ب",
        highway42: "الطريق السريع 42",
        northForest: "الغابة الشمالية",
        tenMinsAgo: "منذ 10 دقائق",
        oneHourAgo: "منذ ساعة",
        twoHoursAgo: "منذ ساعتين",
        fiveMinsAgo: "منذ 5 دقائق",

        operationalOverview: "نظرة عامة تشغيلية",
        realTimeAwareness: "الوعي بالموقف في الوقت الفعلي",
        incidentTrends: "اتجاهات الحوادث",
        resourceStatus: "حالة الموارد",
        recentAlerts: "التنبيهات الحرجة الأخيرة",
        vsLastWeek: "مقارنة بالأسبوع الماضي",
        improvement: "تحسن",
        time: "الوقت",
        status: "الحالة",
        active: "نشط",
        inactive: "غير نشط",
        activate: "تنشيط",
        saveChanges: "حفظ التغييرات",
        cancel: "إلغاء",
        alertDeactivated: "تم تعطيل التنبيه بنجاح",
        alertActivated: "تم تنشيط التنبيه بنجاح",
        newAlert: "تنبيه جديد",
        alertTitle: "عنوان التنبيه",
        alertType: "نوع التنبيه",
        selectType: "اختر النوع",
        broadcastAlert: "بث التنبيه",
        critical: "حرج",
        high: "مرتفع",
        responding: "قيد الاستجابة",
        resolved: "تم الحل",
        newIncidents: "حوادث جديدة",
        available: "متاح",
        deployed: "منشر",
        maintenance: "صيانة",
        mon: "الاثنين", tue: "الثلاثاء", wed: "الأربعاء", thu: "الخميس", fri: "الجمعة", sat: "السبت", sun: "الأحد",
        flashFlood: "فيضان مفاجئ",
        powerOutage: "انقطاع الكهرباء في المستشفى",
        northZone: "منطقة أ - المنطقة الشمالية",
        hospitalLocation: "مستشفى المدينة العام",
        minsAgo: "منذ دقائق",
        mins: "د",

        // Logistics Page
        resourceManagement: "إدارة الموارد",
        trackAllocateAssets: "تتبع وتخصيص الأصول",
        inventory: "المخزون",
        hospitalsTab: "المستشفيات",
        volunteersTab: "المتطوعون",
        searchResources: "البحث عن الموارد...",
        beds: "الأسرة",
        icu: "العناية المركزة",
        units: "وحدات",
        full: "ممتلئ",

        // Logistics Data
        firstAid: "الإسعافات الأولية",
        searchAndRescue: "البحث والإنقاذ",
        warehouseA: "المستودع أ",
        warehouseB: "المستودع ب",
        centralDepot: "المستودع المركزي",
        foodPackets: "طرود غذائية",
        blankets: "بطانيات",
        medKits: "أطقم طبية",
        cityGeneral: "مستشفى المدينة العام",
        memorialHospital: "مستشفى ميموريال",

        copyright: "© 2025 نظام إدارة الكوارث",
        system: "النظام",
        core: "الأساسي",
        location: "الموقع",
        totalLogs: "السجلات الإجمالية"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

    useEffect(() => {
        localStorage.setItem('language', language);
        // Handle RTL for Arabic
        if (language === 'ar') {
            document.documentElement.dir = 'rtl';
            document.documentElement.lang = 'ar';
        } else {
            document.documentElement.dir = 'ltr';
            document.documentElement.lang = language;
        }
    }, [language]);

    const t = (key) => {
        return translations[language]?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
